Repository sb03-deokhugam-team2/sb03-deokhugam-team2, pull requests merged in 2025-07, with the labels that each got.

#59 Feature: 인기 도서 점수 계산 배치 기능 구현
  src/main/java/com/twogether/deokhugam/DeokhugamApplication.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/PopularBookBatchService.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/PopularBookRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/dto/BookScoreDto.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PopularBookRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PopularReviewRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PowerUserRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/repository/PopularBookRankingRepository.java
  src/main/java/com/twogether/deokhugam/notification/dto/NotificationDto.java
  src/main/java/com/twogether/deokhugam/notification/dto/NotificationUpdateRequest.java
  src/main/java/com/twogether/deokhugam/notification/entity/Notification.java
  src/main/java/com/twogether/deokhugam/review/repository/ReviewRepository.java
  src/main/java/com/twogether/deokhugam/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/twogether/deokhugam/review/repository/custom/ReviewRepositoryImpl.java
  src/main/resources/SCHEMA.sql
  src/test/java/com/twogether/deokhugam/dashboard/batch/PopularBookBatchServiceTest.java
Labels: 상

#63 Feature: 댓글 등록 기능 구현
  src/main/java/com/twogether/deokhugam/comments/controller/CommentController.java
  src/main/java/com/twogether/deokhugam/comments/dto/CommentCreateRequest.java
  src/main/java/com/twogether/deokhugam/comments/entity/Comment.java
  src/main/java/com/twogether/deokhugam/comments/mapper/CommentMapper.java
  src/main/java/com/twogether/deokhugam/comments/repository/CommentRepository.java
  src/main/java/com/twogether/deokhugam/comments/service/CommentService.java
  src/test/java/com/twogether/deokhugam/comments/CommentServiceTest.java
Labels: 상

#72 Fix: 인기 도서 점수 계산 배치 기능 수정
  build.gradle
  src/main/java/com/twogether/deokhugam/common/exception/ErrorCode.java
  src/main/java/com/twogether/deokhugam/config/RankingBatchJobConfig.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/BookScoreProcessor.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/JpaBookScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/PopularBookBatchService.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/PopularBookRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/PopularBookRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PopularBookRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/RankingPeriod.java
  src/main/java/com/twogether/deokhugam/dashboard/repository/PopularBookRankingRepository.java
  src/main/java/com/twogether/deokhugam/review/repository/ReviewRepository.java
  src/main/java/com/twogether/deokhugam/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/twogether/deokhugam/review/repository/custom/ReviewRepositoryImpl.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/test/java/com/twogether/deokhugam/dashboard/BookScoreProcessorTest.java
  src/test/java/com/twogether/deokhugam/dashboard/PopularBookRankingJobIntegrationTest.java
  src/test/java/com/twogether/deokhugam/dashboard/PopularBookRankingWriterTest.java
  src/test/resources/application-test.yaml
  src/test/resources/schema-test.sql
  src/test/resources/sql/popular_book_ranking_test_data.sql
Labels: 상

#71 Feature: 리뷰 댓글 목록 조회 기능 구현
  src/main/java/com/twogether/deokhugam/comments/controller/CommentController.java
  src/main/java/com/twogether/deokhugam/comments/entity/Comment.java
  src/main/java/com/twogether/deokhugam/comments/mapper/CommentMapper.java
  src/main/java/com/twogether/deokhugam/comments/repository/CommentRepository.java
  src/main/java/com/twogether/deokhugam/comments/repository/CommentRepositoryCustom.java
  src/main/java/com/twogether/deokhugam/comments/repository/CommentRepositoryImpl.java
  src/main/java/com/twogether/deokhugam/comments/service/CommentQueryService.java
  src/test/java/com/twogether/deokhugam/comments/controller/CommentControllerTest.java
  src/test/java/com/twogether/deokhugam/comments/service/CommentQueryServiceTest.java
  src/test/java/com/twogether/deokhugam/comments/service/CommentServiceTest.java
Labels: 상

#75 Feature: 외부 API 관련 application.yaml 구문 추가 및 Book더미 썸네일 주소 내재화
  src/main/resources/application.yaml
  src/main/resources/dummy/book_dummy.sql
Labels: 하

#79 Feature: 인기 리뷰 점수 계산 배치 기능 구현
  src/main/java/com/twogether/deokhugam/config/RankingBatchJobConfig.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/model/ReviewScoreDto.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/processor/BookScoreProcessor.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/processor/ReviewScoreProcessor.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaBookScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaReviewScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularBookRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularReviewRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularBookRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularReviewRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PopularReviewRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/repository/PopularReviewRankingRepository.java
  src/main/resources/application.yaml
  src/test/java/com/twogether/deokhugam/dashboard/book/BookScoreProcessorTest.java
  src/test/java/com/twogether/deokhugam/dashboard/book/PopularBookRankingBatchTest.java
  src/test/java/com/twogether/deokhugam/dashboard/book/PopularBookRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/dashboard/review/PopularReviewRankingBatchTest.java
  src/test/java/com/twogether/deokhugam/dashboard/review/PopularReviewRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/dashboard/review/ReviewScoreProcessorTest.java
  src/test/resources/application-test.yaml
  src/test/resources/sql/popular_book_ranking_test_data.sql
  src/test/resources/sql/popular_review_ranking_test_data.sql
Labels: 상

#84 Feature: 파워 유저 점수 계산 배치 기능 구현
  src/main/java/com/twogether/deokhugam/config/RankingBatchJobConfig.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/model/PowerUserScoreDto.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/processor/PowerUserScoreProcessor.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaPowerUserScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PowerUserRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PowerUserRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/entity/PowerUserRanking.java
  src/main/java/com/twogether/deokhugam/dashboard/repository/PowerUserRankingRepository.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingBatchTest.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserScoreProcessorTest.java
  src/test/resources/sql/power_user_ranking_test_data.sql
Labels: 상

#89 Feature: 알림 목록 조회 기능 구현
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaPowerUserScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularBookRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularReviewRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PowerUserRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularReviewRankingWriter.java
  src/main/java/com/twogether/deokhugam/notification/controller/NotificationController.java
  src/main/java/com/twogether/deokhugam/notification/repository/NotificationRepository.java
  src/main/java/com/twogether/deokhugam/notification/service/NotificationQueryService.java
  src/main/java/com/twogether/deokhugam/review/service/BasicReviewService.java
  src/main/resources/SCHEMA.sql
  src/main/resources/application.yaml
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingBatchTest.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/notification/NotificationControllerTest.java
  src/test/java/com/twogether/deokhugam/notification/NotificationQueryServiceTest.java
  src/test/java/com/twogether/deokhugam/notification/NotificationServiceTest.java
  src/test/resources/sql/power_user_ranking_test_data.sql
Labels: 중

#93 Feature: 알림 단건 읽음 처리 기능 구현
  src/main/java/com/twogether/deokhugam/common/exception/ErrorCode.java
  src/main/java/com/twogether/deokhugam/common/exception/GlobalExceptionHandler.java
  src/main/java/com/twogether/deokhugam/notification/controller/NotificationController.java
  src/main/java/com/twogether/deokhugam/notification/dto/NotificationUpdateRequest.java
  src/main/java/com/twogether/deokhugam/notification/entity/Notification.java
  src/main/java/com/twogether/deokhugam/notification/exception/NotificationNotFoundException.java
  src/main/java/com/twogether/deokhugam/notification/repository/NotificationRepository.java
  src/main/java/com/twogether/deokhugam/notification/service/NotificationService.java
  src/test/java/com/twogether/deokhugam/notification/NotificationControllerTest.java
  src/test/java/com/twogether/deokhugam/notification/NotificationServiceTest.java
Labels: 하

#105 Feature: 읽은 알림 자동 삭제 배치 구현
  src/main/java/com/twogether/deokhugam/config/NotificationCleanupJobConfig.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularBookRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PopularReviewRankingScheduler.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/scheduler/PowerUserRankingScheduler.java
  src/main/java/com/twogether/deokhugam/notification/batch/reader/JpaNotificationReader.java
  src/main/java/com/twogether/deokhugam/notification/batch/scheduler/NotificationCleanupScheduler.java
  src/main/java/com/twogether/deokhugam/notification/batch/writer/NotificationDeleteWriter.java
  src/main/java/com/twogether/deokhugam/notification/repository/NotificationRepository.java
  src/main/resources/application.yaml
  src/test/java/com/twogether/deokhugam/notification/batch/JpaNotificationReaderTest.java
  src/test/java/com/twogether/deokhugam/notification/batch/NotificationCleanupJobTest.java
  src/test/java/com/twogether/deokhugam/notification/batch/NotificationDeleteWriterTest.java
  src/test/resources/sql/notification_cleanup_test.sql
Labels: 하

#119 Refactor: 알림 삭제 기준 원래 상태로 복구
  src/main/java/com/twogether/deokhugam/notification/batch/reader/JpaNotificationReader.java
Labels: 테스트

#120 Fix: 리뷰 조회 예외 테스트에 누락된 Mock 설정 추가
  src/test/java/com/twogether/deokhugam/review/service/BasicReviewServiceTest.java
Labels: 테스트

#124 Test: NotificationQueryService 및 TimeParameterUtil 커버리지 보완
  src/main/java/com/twogether/deokhugam/notification/repository/NotificationRepository.java
  src/main/java/com/twogether/deokhugam/notification/service/NotificationQueryService.java
  src/test/java/com/twogether/deokhugam/common/util/TimeParameterUtilTest.java
  src/test/java/com/twogether/deokhugam/notification/NotificationQueryServiceTest.java
Labels: 테스트

#126 Fix: 인기 리뷰 랭킹 조회 시 점수 기준 정렬 적용
  src/main/java/com/twogether/deokhugam/dashboard/repository/PopularReviewRankingCustomRepositoryImpl.java
Labels: 테스트, 상

#129 Fix: 인기 리뷰 정렬을 점수에서 랭크로 변경
  src/main/java/com/twogether/deokhugam/dashboard/repository/PopularReviewRankingCustomRepositoryImpl.java
Labels: 테스트

#135 Fix: db에 제대로 된 랭킹 형성 안되는 문제 해결
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularBookRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularReviewRankingWriter.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PowerUserRankingWriter.java
  src/test/java/com/twogether/deokhugam/dashboard/book/PopularBookRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/dashboard/review/PopularReviewRankingWriterTest.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingWriterTest.java
Labels: 테스트

#148 Fix: 대시보드 전체 기간 누락 문제 수정 및 점수 정규화 개선
  src/main/java/com/twogether/deokhugam/dashboard/batch/model/PowerUserScoreDto.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaBookScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaPowerUserScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaReviewScoreReader.java
  src/test/java/com/twogether/deokhugam/dashboard/model/PowerUserScoreDtoTest.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserRankingBatchTest.java
Labels: 상

#149 Fix: ALL_TIME 기간에 createdAt 필터 조건 제거
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaBookScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaPowerUserScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaReviewScoreReader.java
  src/test/resources/application-test.yaml
  src/test/resources/schema-test.sql
  src/test/resources/sql/popular_ranking_test_data.sql
Labels: 상

#151 Fix: 인기리뷰 전체부분 수정
  src/main/java/com/twogether/deokhugam/common/exception/DeokhugamException.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaReviewScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/writer/PopularReviewRankingWriter.java
  src/test/java/com/twogether/deokhugam/dashboard/review/PopularReviewRankingWriterTest.java
Labels: 상

#152 Fix: 인기 리뷰 및 파워 유저 누락 수정
  src/main/java/com/twogether/deokhugam/config/RankingBatchJobConfig.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/processor/PowerUserScoreProcessor.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaPowerUserScoreReader.java
  src/main/java/com/twogether/deokhugam/dashboard/batch/reader/JpaReviewScoreReader.java
  src/test/java/com/twogether/deokhugam/dashboard/user/PowerUserScoreProcessorTest.java
Labels: 상
